app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

website/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('search/<str:method>', views.search, name='search'),
    path('search', views.search, name='search'),
    path('export-to-pdf/<metal_ring>', views.get_report, name='get_report'),
    path('map', views.map, name='map'),
    path('observations', views.observations, name='observations'),
    path('remove-plover/<str:id>', views.remove_plover_from_session,
         name='remove_plover_from_session'),
    path('validation', views.validate_plovers, name='validate_plovers'),
]

website/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

SEX_CHOICES = (
    ('M', _('Male')),
    ('F', _('Female')),
    ('U', _('Undetermined'))
)

COLOR_CHOICES = (
    ('R', _('Red')),
    ('P', _('Pink')),
    ('W', _('White')),
    ('Y', _('Yellow')),
    ('G', _('Green'))
)


class Location(models.Model):
    def __str__(self):
        return (f'{self.town} - {self.locality},'
                f' {self.department} ({self.country})')

    class Meta:
        verbose_name = _('Location')
        verbose_name_plural = _('Locations')

    @property
    def minimal_location(self):
        return f'{self.town} ({self.country})'

    country = models.CharField(max_length=255, verbose_name=_('Country'))
    town = models.CharField(max_length=255, verbose_name=_('Town'))
    department = models.CharField(max_length=255, verbose_name=_('Department'))
    locality = models.CharField(
        max_length=255,
        null=True,
        verbose_name=_('Locality')
    )


class Observer(models.Model):
    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = _('Observer')
        verbose_name_plural = _('Observers')

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    last_name = models.CharField(max_length=255, verbose_name=_('Last name'))
    first_name = models.CharField(max_length=255, verbose_name=_('First name'))
    email = models.EmailField(
        max_length=254,
        verbose_name=_('Email'),
        null=True
    )
    is_bander = models.BooleanField(default=False, verbose_name=_('Is bander'))


class Plover(models.Model):
    def __str__(self):
        return f'{self.code} {self.get_color_display()} ({self.metal_ring})'

    class Meta:
        unique_together = ('metal_ring', 'code', 'color')
        verbose_name = _('Kentish plover')
        verbose_name_plural = _('Kentish plovers')

    bander = models.ForeignKey(
        Observer,
        related_name='plovers',
        on_delete=models.PROTECT,
        verbose_name=_('Bander')
    )
    location = models.ForeignKey(
        Location,
        related_name='plovers',
        on_delete=models.PROTECT,
        verbose_name=_('Location')
    )
    banding_year = models.IntegerField(
        blank=True,
        null=True,
        verbose_name=_('Banding year')
    )
    metal_ring = models.CharField(
        max_length=20,
        unique=True,
        verbose_name=_('Metal ring')
    )
    code = models.IntegerField(verbose_name=_('Code'))
    color = models.CharField(
        choices=COLOR_CHOICES,
        max_length=1,
        default=0,
        null=True,
        verbose_name=_('Color')
    )
    sex = models.CharField(
        choices=SEX_CHOICES,
        max_length=20,
        default=2,
        null=True,
        verbose_name=_('Sex')
    )
    age = models.CharField(max_length=5, verbose_name=_('Age'))
    banding_date = models.DateField(
        blank=True,
        null=True,
        verbose_name=_('Banding date')
    )
    banding_time = models.TimeField(
        blank=True,
        null=True,
        verbose_name=_('Banding time')
    )


class Observation(models.Model):
    def __str__(self):
        return f'{self.date} {self.observer} : {self.plover} - {self.location}'

    class Meta:
        verbose_name = _('Observation')
        verbose_name_plural = _('Observations')
        ordering = ['-date']

    observer = models.ForeignKey(
        Observer,
        related_name='observations',
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=_('Observer')
    )
    plover = models.ForeignKey(
        Plover,
        related_name='observations',
        on_delete=models.CASCADE,
        verbose_name=_('Plover')
    )
    location = models.ForeignKey(
        Location,
        related_name='observations',
        on_delete=models.CASCADE,
        verbose_name=_('Location')
    )
    date = models.DateField(verbose_name=_('Date'))
    supposed_sex = models.CharField(
        choices=SEX_CHOICES,
        max_length=20,
        default=2,
        verbose_name=_('Supposed Sex')
    )
    coordinate_x = models.FloatField(null=True, verbose_name=_('X coordinate'))
    coordinate_y = models.FloatField(null=True, verbose_name=_('Y coordinate'))
    comment = models.TextField(null=True, verbose_name=_('Comment'))

website/forms.py
from django import forms
from website.models import COLOR_CHOICES, SEX_CHOICES
from django.utils.translation import ugettext_lazy as _


class InputsTemplates():

    @staticmethod
    def choicefield_input(label, choices):
        return forms.ChoiceField(
            label=label,
            choices=choices,
            widget=forms.Select(attrs={'class': 'form-control'})
        )

    @staticmethod
    def charfield_template(label, max_length, required=True):
        return forms.CharField(
            label=label,
            required=required,
            max_length=max_length,
            widget=forms.TextInput(attrs={'class': 'form-control'})
        )

    @staticmethod
    def code_input(required=True):
        return forms.IntegerField(
            localize=False,
            label=_('Code'),
            required=required,
            widget=forms.NumberInput(attrs={'class': 'form-control'})
        )

    @staticmethod
    def coordinatefield_template(label):
        return forms.FloatField(
            label=label,
            required=False,
            widget=forms.NumberInput(attrs={
                'class': 'form-control',
                'readonly': True
            })
        )


class CodeForm(forms.Form):
    code = InputsTemplates.code_input()
    color = InputsTemplates.choicefield_input(_('Color'), COLOR_CHOICES)


class MetalForm(forms.Form):
    metal_ring = InputsTemplates.charfield_template(_('Metal ring'), 10)


class MapForm(forms.Form):
    date = forms.DateField(
        label=_('Date'),
        widget=forms.DateInput(attrs={
            'type': 'date',
            'class': 'form-control'
        })
    )

    last_name = InputsTemplates.charfield_template(_('Last name'), 255)
    first_name = InputsTemplates.charfield_template(_('First name'), 255)
    town = InputsTemplates.charfield_template(_('Town'), 255)
    department = InputsTemplates.charfield_template(_('Department'), 255)
    country = InputsTemplates.charfield_template(_('Country'), 255)
    locality = InputsTemplates.charfield_template(_('Locality'), 255, False)

    coordinate_x = InputsTemplates.coordinatefield_template(_('X coordinate'))
    coordinate_y = InputsTemplates.coordinatefield_template(_('Y coordinate'))


class PloverForm(forms.Form):
    code = InputsTemplates.code_input()
    color = InputsTemplates.choicefield_input(_('Color'), COLOR_CHOICES)
    sex = InputsTemplates.choicefield_input(_('Sex'), SEX_CHOICES)
    comment = forms.CharField(
        label=_('Comment'),
        required=False,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'rows': 3
        })
    )

website/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import get_template
from website.utils.views_snippets import get_or_none, flush_session
from website.models import Plover, Observation, Location, Observer
from django.conf import settings
from django.http import HttpResponse
from website.forms import CodeForm, MetalForm, MapForm, PloverForm

from weasyprint import HTML, CSS
from os import getenv
from hashlib import sha1


def index(request):
    return render(request, 'website/home.html')


def search(request, method=None):
    if method is None or (method != 'code' and method != 'metal'):
        return redirect('search', method='code')

    plover = None
    form = None
    if method == 'code':
        if request.method == 'POST':
            plover = get_or_none(
                Plover, code=request.POST.get('code'),
                color=request.POST.get('color'))
        form = CodeForm
    else:
        if request.method == 'POST':
            plover = get_or_none(
                Plover, metal_ring=request.POST.get('metal_ring').strip())
        form = MetalForm

    data = {
        'not_found': False,
        'form_url': request.path
    }

    if request.method == 'POST':
        form = form(request.POST)

        if form.is_valid():
            if plover:
                data['plover'] = plover
            else:
                data['not_found'] = True
    else:
        form = form()

    data['form'] = form
    return render(request, 'website/search.html', data)


def get_report(request, metal_ring):
    plover = get_object_or_404(Plover, metal_ring=metal_ring)
    html_template = get_template('website/pdf_export.html')
    static_path = f'{settings.BASE_DIR}{settings.STATIC_URL}'

    pdf_file = HTML(
        string=html_template.render(
            {'plover': plover}).encode(encoding="UTF-8"),
        base_url=request.build_absolute_uri()
    ).write_pdf(stylesheets=[
        CSS('https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css'),
        CSS(f'{static_path}css/pdf.css')
    ])

    response = HttpResponse(pdf_file, content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{metal_ring}.pdf"'

    return response


def map(request):
    flush_session(request, ('plovers', 'general'))

    if request.method == 'POST':
        map_form = MapForm(request.POST)

        # check whether it's valid:
        if map_form.is_valid():
            request.session['general'] = {
                'date': request.POST.get('date'),
                'last_name': request.POST.get('last_name').strip().upper(),
                'first_name': request.POST.get('first_name').strip().capitalize(),
                'town': request.POST.get('town').strip().capitalize(),
                'department': request.POST.get('department'),
                'country': request.POST.get('country').strip().capitalize(),
                'locality': request.POST.get('locality').strip().capitalize(),
                'coordinate_x': request.POST.get('coordinate_x'),
                'coordinate_y': request.POST.get('coordinate_y')
            }

            return redirect('observations')
    else:
        map_form = MapForm()

    return render(request, 'website/map.html', {
        'form': map_form,
        'google_map_api_key': getenv("GOOGLE_MAP_API_KEY")
    })


def remove_plover_from_session(request, id):
    plovers = request.session.get('plovers')
    plovers.pop(id, None)
    request.session['plovers'] = plovers

    return redirect('observations')


def observations(request):
    def add_plover_in_session(request, plover):
        if 'plovers' not in request.session or not request.session['plovers']:
            plovers = {}
        else:
            plovers = request.session['plovers']

        plovers[plover.get('id')] = plover
        request.session['plovers'] = plovers

    if request.session.get('general', False):
        data = {
            'general': request.session.get('general')
        }

        if request.method == 'POST':
            plover_form = PloverForm(request.POST)

            if plover_form.is_valid():
                form_data = plover_form.cleaned_data
                id = sha1(f"{form_data['code']}{form_data['color']}".encode())
                plover = {
                    'id': id.hexdigest(),
                    'code': form_data['code'],
                    'color': form_data['color'],
                    'sex': form_data['sex'],
                    'comment': form_data['comment'].strip(),
                }

                add_plover_in_session(request, plover)
                data['plovers'] = request.session.get('plovers').values()
        elif request.session.get('plovers', False):
            data['plovers'] = request.session.get('plovers').values()
            plover_form = PloverForm()
        else:
            plover_form = PloverForm()

        data['form'] = plover_form
        return render(request, 'website/observations.html', data)
    else:
        return redirect('map')


def validate_plovers(request):
    def parse_form_coords(coord):
        coord = coord.strip()
        return float(coord) if coord else None

    general = request.session.get('general')
    observations = request.session.get('plovers').values()
    accepted_observations = []
    rejected_observations = []

    location, location_created = Location.objects.get_or_create(
        country=general.get('country'),
        town=general.get('town'),
        department=general.get('department'),
        locality=general.get('locality')
    )

    observer, observer_created = Observer.objects.get_or_create(
        last_name=general.get('last_name'),
        first_name=general.get('first_name'),
        email=general.get('email')
    )

    for observation in observations:
        try:
            plover = Plover.objects.get(
                code=observation.get('code'),
                color=observation.get('color')
            )
        except Plover.DoesNotExist:
            plover = None

        if plover:
            observation_saved, created = Observation.objects.get_or_create(
                observer=observer,
                location=location,
                plover=plover,
                date=general.get('date'),
                supposed_sex=observation.get('sex'),
                comment=observation.get('comment'),
                coordinate_x=parse_form_coords(general.get('coordinate_x')),
                coordinate_y=parse_form_coords(general.get('coordinate_y'))
            )

            accepted_observations.append(plover)
        else:
            rejected_observations.append(observation)

    result = {
        'accepted_observations': accepted_observations,
        'rejected_observations': rejected_observations
    }

    return render(request, 'website/result.html', result)

templates/website/home.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% translate "Home" %}{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mt-5">Banding-Tracking</h1>
    <p class="lead">{% blocktrans %}Study tool for ringed birds' populations{% endblocktrans %}</p>
</div>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                {% trans "Record observations" as title %}
                {% include "common/home_card.html" with src="/map" picture="img/plover.jpg" alt=title title=title %}
            </div>

            <div class="col-md-4">
                {% trans "GONm website" as alt %}
                {% trans "The GONm" as title %}
                {% include "common/home_card.html" with src="http://www.gonm.org/" target="_blank" picture="img/gonm.jpg" alt=alt title=title %}
            </div>

            <div class="col-md-4">
                {% trans "Bretagne vivante" as title %}
                {% include "common/home_card.html" with src="http://www.bretagne-vivante-dev.org/gravelot/index.php" target="_blank" picture="img/bretagne_vivante.jpg" alt=title title=title %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/website/map.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Record your observations" %}{% endblock %}
{% block content %}

<section class="container py-lg-3">
    <form method="post" action="{% url 'map' %}" class="mt-5">
        {% csrf_token %}
        <h1>1. {% trans "General informations" %}</h1>
        <p class="fst-italic">
            {% trans "Please fill the date of your observation & your personal information to contact you if needed" %}
        </p>
        <div class="row mb-3">
            {% include "common/field.html" with field=form.date %}
        </div>
        <div class="row mb-3">
            {% include "common/field.html" with field=form.last_name %}
            {% include "common/field.html" with field=form.first_name %}
        </div>

        <hr />

        <h1>2. {% trans "Localize your observation" %}</h1>
        <p class="fst-italic">
            {% trans "You can click on the map to localize your observation or fill the form by hand" %}
        </p>
        <div id="map" class="map-form"></div>
        <div class="row mb-3">
            {% include "common/field.html" with field=form.town %}
            {% include "common/field.html" with field=form.department %}
            {% include "common/field.html" with field=form.country %}
        </div>
        <div class="row mb-3">
            {% include "common/field.html" with field=form.locality %}
        </div>
        <div class="row mb-3">
            {% include "common/field.html" with field=form.coordinate_x %}
            {% include "common/field.html" with field=form.coordinate_y %}
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
        </div>
    </form>
</section>
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
const reverseGeocode = (location) => {
    const parseAddress = (addressObject, index) => {
        let addressComponent = '';
        try {
            addressComponent = addressObject.address_components[index].long_name;
        } catch (e) {
            // TODO: Display a popup instead of an infoWindow
            console.error("Can't get all the components of the formatted address");
            console.error(e);
        }

        return addressComponent
    }

    const geocoder = new google.maps.Geocoder();
    geocoder.geocode({ 'location': location }, function (results, status) {
        if (status === google.maps.GeocoderStatus.OK) {
            if (results[0]) {
                const addressObject = results[0];

                // Fill the form
                document.querySelector('input[name=coordinate_x]').value = location.lat();
                document.querySelector('input[name=coordinate_y]').value = location.lng();
                document.querySelector('input[name=town]').value = parseAddress(addressObject, 2);
                document.querySelector('input[name=department]').value = parseAddress(addressObject, 3);
                document.querySelector('input[name=country]').value = parseAddress(addressObject, 4);
            }
        } else {
            // TODO: Display a popup instead of an infoWindow
            console.error('Geocoder failed due to: ' + status);
        }
    });
}

function initMap() {
    let markers = [];

    const setPosition = (latLng) => {
        for (var i = 0; i < markers.length; i++) {
            markers[i].setMap(null);
        }
        const marker = new google.maps.Marker({
            position: latLng,
            map: map
        });

        // Center the map on the marker
        markers.push(marker);
        map.panTo(latLng);
        reverseGeocode(latLng);
    }

    let INIT_LAT = 49.174924;
    let INIT_LNG = -0.339841;

    {% if form.coordinate_x.value and form.coordinate_x.value %}
    INIT_LAT = {{form.coordinate_x.value}};
    INIT_LNG = {{form.coordinate_y.value}};
    {% endif %}

    const map = new google.maps.Map(document.getElementById('map'), {
        center: { lat: INIT_LAT, lng: INIT_LNG },
        zoom: 15
    });

    map.addListener('click', function(e) { setPosition(e.latLng); });
}
</script>

<!-- Google map API -->
<script src="https://maps.googleapis.com/maps/api/js?callback=initMap&key={{ google_map_api_key }}"></script>
{% endblock %}

templates/website/observations.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load template_filters %}

{% block title %}{% trans "Record your observations" %}{% endblock %}
{% block content %}
<section class="container py-lg-3">
    <h1>{% trans "Record your observations" %}</h1>

    <p>
        <b>{% trans "Date" %} :</b> {{general.date}}<br>
        <b>{% trans "Observer" %} :</b> {{general.last_name}} {{general.first_name}}<br>
        <b>{% trans "Location" %} :</b> {{general.town}}, {{general.department}}
    </p>

    <p class="fst-italic">
        {% trans "Fill all the combinations reported on the place & day you gave in the previous page." %}
        {% trans 'If you finised to record all the observations for that place & time, you can click on "Send my observations" to get the history of the birds.' %}
    </p>
    <p class="fst-italic">
        {% trans "If one of the combinaison isn't recognised by the database, you will be notified." %}
    <p>

    <div class="row">
        <div class="col-sm-8">
            <h2>{% trans "Record observations" %}</h2>
            <form method="post" action="{% url 'observations' %}" autocomplete="off">
                {% csrf_token %}
                {% for field in form %}
                <div class="row mb-3">
                    {% include "common/field.html" with field=field %}
                </div>
                {% endfor %}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">{% trans "Add my observation" %}</button>
                </div>
            </form>
        </div>

        <div class="col-sm-4">
            <h2>{% trans "All the plovers already seized" %}</h2>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>{% trans "Code" %}</th>
                    <th>{% trans "Color" %}</th>
                    <th>{% trans "Sex" %}</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for plover in plovers %}
                    <tr>
                    <td>{{plover.code}}</td>
                    <td>{{plover.color|color_to_string}}</td>
                    <td>{{plover.sex|sex_to_string}}</td>
                    <td>
                        <a href="{% url 'remove_plover_from_session' plover.id %}">
                            <img src="{% static 'img/trash-fill.svg' %}" alt="{% trans 'Delete the observation' %}">
                        </a>
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            
            {% if plovers %}
                <a href="{% url 'validate_plovers' %}" class="btn btn-secondary large-button" role="button" {% if not plovers %}disabled{% endif %}>
                    {% trans "Send my observations" %}
                </a>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

templates/website/pdf_export.html
{% load i18n %}
{% load static %}

{% get_current_language as LANGUAGE_CODE %}

<!doctype html>
<html lang="{{ LANGUAGE_CODE }}">

<head>
    <meta charset="utf-8">
</head>

<body>
<table class="header">
    <thead>
        <th>
            <td>
                <img class="resume-logo" src="{% static 'img/square_gonm.png' %}" alt="{% trans 'GONm logo' %}">
            </td>
        <th>
        </th>
            <td align="center">
                <h3 class="text-center">{% trans "Summary of all sightings for the banded Kentish plover" %}<b></b></h3>
                <h4 class="text-center"><i>{% trans "Charadrius alexandrinus" %}</i></h4>
            </td>
        </th>
    </thead>
</table>

{% include "common/bird_resume.html" with header_split=False %}
</body>

templates/website/result.html
{% extends "base.html" %}
{% load i18n %}
{% load template_filters %}

{% block title %}{% trans "Result" %}{% endblock %}
{% block content %}
<section class="container py-lg-3">
    <h2 class="mb-3">{% trans "Result" %}</h2>
    
    {% if rejected_observations %}
    <h3 class="mb-3">{% trans "Rejected observations" %}</h3>
    <ul>
        {% for observation in rejected_observations %}
        <li>{{observation.code}} {{observation.color|color_to_string}}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% if rejected_observations and accepted_observations %}<hr>{% endif %}

    {% if accepted_observations %}
    <h3>{% trans "Observations accepted" %}</h3>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>{% trans 'Number' %}</th>
            <th>{% trans 'Color' %}</th>
            <th>{% trans 'Sex' %}</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for plover in accepted_observations %}
            <tr>
            <td>{{plover.code}}</td>
            <td>{{plover.get_color_display}}</td>
            <td>{{plover.get_sex_display}}</td>
            <td>
                <a href="{% url 'get_report' plover.metal_ring %}">
                    <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                    {% trans "Download into PDF" %}
                </a>
            </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}

    <a href="{% url 'map' %}" class="btn btn-primary large-button" role="button">
        {% trans "Go back to the form" %}
    </a>
</section>
{% endblock %}

templates/website/search.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Search" %}{% endblock %}

{% block content %}
<section class="container py-lg-3">
    <h2>{% trans "Search a plover" %}</h2>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if form_url == '/search/metal' %} active{% endif %}" href="{% url 'search' method='metal' %}">
                {% trans "Search by metal ring code" %}
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if form_url == '/search/code' %} active{% endif %}" href="{% url 'search' method='code' %}">
                {% trans "Search by color code" %}
            </a>
        </li>
    </ul>

    <div class="tab-content my-3">
        <form method="post" action="{{form_url}}" autocomplete="off">
            {% csrf_token %}
            <div class="row mb-3">
                {% for field in form %} {% include "common/field.html" with field=field %} {% endfor %}
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-primary">{% trans "Search" %}</button>
            </div>
        </form>
    </div>

    {% if plover %}
    <hr />

    <a href="{% url 'get_report' plover.metal_ring %}" class="btn btn-secondary large-button" role="button">
        <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
        {% trans "Download into PDF" %}
    </a>

    <div class="row flex-sm-row-reverse mb-3">
        <div class="col-md-4">
            <div class="thumbnail d-flex justify-content-center align-items-center flex-column">
                <img class="d-block resume-logo" src="{% static 'img/square_gonm.png' %}" alt="{% trans 'GONm logo' %}">
            </div>
        </div>
        <div class="col-md-8 d-flex justify-content-center align-items-center flex-column">
            <h3 class="text-center">{% trans "Summary of all sightings for the banded Kentish plover" %}<b></b></h3>
            <h4 class="text-center"><i>{% trans "Charadrius alexandrinus" %}</i></h4>
        </div>
    </div>

    {% include "common/bird_resume.html" with header_split=True %}
    {% endif %}

    {% if not_found %}
    <div class="alert alert-warning" role="alert">
        {% trans "Can't find any plover related to the given informations" %}
    </div>
    {% endif %}
</section>
{% endblock %}